### ISSUE TITLE
Powershell script error in splunk logs

### ISSUE THREAD

**Issue by catchvjay** [hkelley/TA-windnsanalytical#1]
Hi hkelley,

Thanks for your work on the app. I have installed the app on splunk forwarder and search head side. When I restart the forwarder services, I am getting following powershell related errors.

Get-WinEvent : No events were found that match the specified selection 
criteria.
At C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WindowsDNSAnalytical\b
in\get_dns_analytics.ps1:1 char:1
+ Get-WinEvent -Oldest -LogName "Microsoft-Windows-DNSServer/Analytical ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingEventsFound,Microsoft.PowerShell.Comma 
   nds.GetWinEventCommand
 
I am also getting same error when I run the script manually. Have you faced such kind of issue or am I missing any configurations?

Regards,
Vijay

**Comment by hkelley** [comment]
I haven’t seen that. 

1). Do you see the events in the Event Viewer UI?
2). If the events are there, perhaps the “init” script may be running (and resetting the logs too often. It’s only supposed to run when the UF restarts.

**Comment by catchvjay** [comment]
Hi, Thanks for quick response. Yes, I am able to see to see the eventys. Infact, now those errors are not appearing and I am able to see logs in splunk. It looks like whenever, I restart the service these errors are appearing but afterwards they are not being seen.

Thanks,
Vijay

**Comment by hkelley** [comment]
I’ll try to improve it by adding a pause before the first log capture (so that some events can build up) and catching the NoMatchingEvents exception.
