### ISSUE TITLE
Only seeing the the following Powershell script related logs in Splunk

### ISSUE THREAD

**Issue by nanjum88** [hkelley/TA-windnsanalytical#2]
I have installed the (TA) add-on on the Domain Controller, where we have the DNS Analytical logs enabled, through Splunk UF using the deployment server,  with a minor change in index name in inputs.conf and indexes.conf to use an existing index , instead of creating a new index dns. 

But I am only seeing the following events coming into Splunk from that source. Do we need to do anything 

INFO [:3240] Script exceeded maximum runtime of .  Terminating PID 3240

Please see the image below (scrubbed host information) - 

![image](https://user-images.githubusercontent.com/32209105/63196756-ebe00f80-c02a-11e9-946d-26054b7115b7.png)

Thanks

**Comment by hkelley** [comment]
A few items to investigate:

- Do you see the script launch time in the _internal index?  How long is it running?
`index=_internal sourcetype=splunkd ExecProcessor get_dns_analytics.ps1`

- Does the get_dns_analytics.ps1 script work if you run it interactively (as admin)?

I'll have to see if there's a bug in the maximum runtime variable.   Do you have the latest version?

![image](https://user-images.githubusercontent.com/8828244/63217531-a5b3aa80-c115-11e9-97ca-5d25f00f3910.png)
