### ISSUE TITLE
props.conf has an invalid regex

### ISSUE THREAD

**Issue by jeevanullas** [hkelley/TA-windnsanalytical#3]
Unfortunately this add-on does not work. The error message I see in one of the log files from the UF says 

07-14-2020 20:51:22.527 WARN  btool-support - Bad regex value: 'Id\s+:\s+(?.*)\s+Message', of param: props.conf / [WinDNS:Analytical] / EXTRACT-win-dns-analytical-event_id; why: unrecognized character after (? or (?-

I tried to modify the regex in question to following 
EXTRACT-win-dns-analytical-event_id = Id\s+:\s+?(.*)\s+Message

This stops the warning but I still do not see the logs in Splunk (index is empty with no events). When I run the script manually it executes just fine. I also tried to pass the flag -SplunkdLogging to see if there were any meaningful logs getting emitted from the manual script execution but it was not helpful.

The following is what I see in the splunkd log file but nothing regarding any script execution afterwards -

07-14-2020 23:40:20.774 +0000 INFO  ExecProcessor - 	interval: 60000 ms
07-14-2020 23:40:20.775 +0000 INFO  ExecProcessor - New scheduled exec process: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1' -SplunkdLogging"
07-14-2020 23:40:20.775 +0000 INFO  ExecProcessor - 	interval: 60000 ms
07-14-2020 23:40:20.775 +0000 INFO  ExecProcessor - New scheduled exec process: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\init_dns_analytics.ps1'"
07-14-2020 23:40:20.775 +0000 INFO  ExecProcessor - 	interval: run once

Any help would be appreciated.

**Comment by hkelley** [comment]
- What Splunk and Python version are you running?   What Windows OS version?   

- What account does the UF run under?

- Have you looked to see if the Powershell process running get_dns_analytics.ps1 is still alive?    If the script runs once but never produces any output then it sounds like it may be hung.

- What output do you see when you run it manually?

**Comment by jeevanullas** [comment]
Splunk version - 7.3.6
Python version - 2.7.18
Windows OS - Windows server 2012 R2
UF runs under the local system account
Both powershell scripts are showing up under Processes and never goes away (until I stop UF).

The UF is installed on windows server and splunk indexer and deployment server is running on Amazon Linux. I can see other logs from the windows server such as event logs showing up on Splunk just not the DNS query logs.

When run manually the script produces the following output (note I have only provided a redacted snippet) -

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1' -SplunkdLogging"


TimeCreated  : 7/15/2020 9:05:59 PM
ProviderName : Microsoft-Windows-DNSServer
Id           : 257
Message      : RESPONSE_SUCCESS: TCP=0; InterfaceIP=; Destination=; AA=0; AD=0;
               QNAME=; QTYPE=1; XID=58571; DNSSEC=0; RCODE=3; Port=; Flags=;
               Scope=Default; Zone=..Cache



INFO [get_dns_analytics.ps1:4604] Writing performance data to STDOUT


LogPausedMs     : 52
DataRetrievalMs : 364
LogFileMaxBytes : 1073741824
LogFileCurBytes : 704512
LoggedRecs      : 613
IgnoredRecs     : 27
LogTimespanSecs : 66036.6097491
ScriptRunSecs   : 8.7353502

**Comment by hkelley** [comment]
That is all very similar to my environment - and the script output looks correct.

I'm assuming that something is hanging the process when it runs under the UF.   Perhap try either:
* running the UF service under your user ID or
* using psexe to run the script interactively as SYSTEM

**Comment by jeevanullas** [comment]
Thanks. Unfortunately these did not help. I then tried to set the execution policy on the host to ByPass with the following command 

Set-ExecutionPolicy ByPass 

and then the scripts do not get hung up. I can now see the DNS Query logs in the index. Meanwhile on the UF logs I see following error message at every script execution (when there is no DNS query logs)  -

07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" New-TimeSpan : Cannot bind parameter 'Start' to the target. Exception setting 
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" "Start": "Object reference not set to an instance of an object."
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" At C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\g
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" et_dns_analytics.ps1:185 char:44
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" + $LoggedTimespanSecs = (New-TimeSpan -Start $logStart -End 
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" $logEnd).TotalSeconds
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'"" +                                            ~~~~~~~~~
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'""     + CategoryInfo          : WriteError: (:) [New-TimeSpan], ParameterBinding 
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'""    Exception
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'""     + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Comm 
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'""    ands.NewTimeSpanCommand
07-16-2020 22:28:08.779 +0000 ERROR ExecProcessor - message from "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "& 'C:\Program Files\SplunkUniversalForwarder\etc\apps\TA-WinDNSAnalytical\bin\get_dns_analytics.ps1'""  
07-16-2020 22:28:28.450 +0000 INFO  TcpOutputProc - Found currently active indexer. Connected to idx=10.0.0.103:9997, reuse=1.

Based on above 2 things and earlier syntax error on regex in props.conf can you let me know if there is a way to first of all run the script without messing around with Execution Policy in such a way, how to avoid the error showing up in the splunkd.log on the UF (it appears to be harmful) and finally if the regex highlighted earlier in my comments need to be modified to avoid the warning.

Thanks for your response.

**Comment by hkelley** [comment]
Project is being archived.
